### Login endpoint
POST {{host}}/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "password123",
  "companyId": {{companyId}}
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### Get order by id
GET {{host}}/company/{{companyId}}/order/{{orderId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get product by id
GET {{host}}/company/{{companyId}}/product/{{productId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Add a new product
POST {{host}}/company/{{companyId}}/product
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Product 1",
  "price": "19.99",
  "description": "This is a sample product",
  "companyId": 1
}

### Add a new order
POST {{host}}/company/{{companyId}}/order
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "companyId": 1,
  "products": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ],
  "clientId": 1,
  "name": "Order 1",
  "totalPrice": "39.99"
}

### Add a new user
POST {{host}}/company/1/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "firstName": "John",
  "lastName": "Doe",
  "username": "abcd",
  "password": "password123",
  "role": "ADMIN",
  "companyId": {{companyId}}
}

### Get user by id
GET {{host}}/company/{{companyId}}/user/{{userId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get company by id
GET {{host}}/company/{{companyId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Add a new company
POST {{host}}/company
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "TEST"
}

