### Login endpoint
POST {{host}}/login
Content-Type: application/json

{
  "companyDomain": "c2",
  "username": "c",
  "password": "p"
}

> {% client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);%}

### Logout endpoint
POST {{host}}/company/{{companyId}}/client/{{clientId}}/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Refresh token endpoint
POST {{host}}/company/{{companyId}}/client/{{clientId}}/refresh-token
Content-Type: application/json

{
  "refreshToken": {{refreshToken}}
}

> {% client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);%}

### CLIENT - Get order by id
GET {{host}}/company/{{companyId}}/client/{{clientId}}/order/{{orderId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### CLIENT - Get orders
GET {{host}}/company/{{companyId}}/client/{{clientId}}/orders
Accept: application/json
Authorization: Bearer {{accessToken}}

### CLIENT - Get product by id
GET {{host}}/company/{{companyId}}/client/product/{{productId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### CLIENT - Add a new order
POST {{host}}/company/{{companyId}}/client/{{clientId}}/order
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "productId": 3,
      "quantity": 2
    },
    {
      "productId": 4,
      "quantity": 1
    }
  ],
  "clientId": {{clientId}},
  "name": "Order 1"
}

### CLIENT - Get company by id
GET {{host}}/company/{{companyId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### CLIENT - Get current user
GET {{host}}/company/{{companyId}}/client
Accept: application/json
Authorization: Bearer {{accessToken}}


### COURIER - Get order by id
GET {{host}}/company/{{companyId}}/courier/{{courierId}}/order/{{orderId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### COURIER - Get orders
GET {{host}}/company/{{companyId}}/courier/{{courierId}}/orders
Accept: application/json
Authorization: Bearer {{accessToken}}


### ADMIN - Get order by id
GET {{host}}/company/{{companyId}}/admin/{{adminId}}/order/{{orderId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### ADMIN - Get product by id
GET {{host}}/company/{{companyId}}/admin/{{adminId}}/product/{{productId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### ADMIN - Add a new product
POST {{host}}/company/{{companyId}}/admin/{{adminId}}/product
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Product 1",
  "price": "19.99",
  "description": "This is a sample product"
}

### ADMIN - Get users
GET {{host}}/company/{{companyId}}/admin/{{adminId}}/users?role=courier
Authorization: Bearer {{accessToken}}
\
### ADMIN - Add a new user
POST {{host}}/company/{{companyId}}/admin/{{adminId}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "firstName": "John",
  "lastName": "Doe",
  "username": "abcdfghi",
  "password": "password123",
  "role": "CLIENT"
}

### ADMIN - Get current user
GET {{host}}/company/{{companyId}}/admin
Accept: application/json
Authorization: Bearer {{accessToken}}

### ADMIN - Get user by id
GET {{host}}/company/{{companyId}}/admin/{{adminId}}/user/{{courierId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### ADMIN - Get company by id
GET {{host}}/company/{{companyId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### ADMIN - Send order
PUT {{host}}/company/{{companyId}}/admin/{{adminId}}/order/18/send?courierId=4
Accept: application/json
Authorization: Bearer {{accessToken}}

